#!/usr/bin/env python

from gtfs_rt_validator_api import validate_gcs_bucket_many

validate_gcs_bucket_many(
    project_id="cal-itp-data-infra",
    token="cloud",
    param_csv="gs://gtfs-data-test/rt-processed/calitp_validation_params/{{execution_date.to_date_string()}}.csv",
    results_bucket="gs://gtfs-data-test/gtfs-rt-validator-api/test-pipeline",
    verbose=True,
    aggregate_counts=True,
    status_result_path="gs://gtfs-data-test/gtfs-rt-validator-api/test-pipeline/status.json",
)
