#!/usr/bin/env python
from multiprocessing import freeze_support

from gtfs_rt_validator_api import validate_gcs_bucket_many

if __name__ == "__main__":
    freeze_support()
    validate_gcs_bucket_many(
        project_id="cal-itp-data-infra",
        token="google_default",
        param_csv="gs://gtfs-data-test/rt-processed/calitp_validation_params/2022-02-01.csv",
        results_bucket="gs://gtfs-data-test/gtfs-rt-validator-api/test-pipeline",
        verbose=True,
        aggregate_counts=True,
        status_result_path="gs://gtfs-data-test/gtfs-rt-validator-api/test-pipeline/status.json",
    )
